<?php

class GuestsTableSeeder extends Seeder {

  public function run()
  {
    DB::table('guests')->delete();

    $guests = array(
      array(
        'code'           => 'DISHANDDRINK',
        'list'           => 'A',
        'attending'      => true,
        'emotion'        => 'pleasure',
        'allow_plusone'  => true,
        'allow_children' => true,
        'guest'          => json_encode(array('first' => 'James', 'last' => 'Dahlfred', 'meal' => 'S')),
        'plusone'        => json_encode(array('first' => 'Leah', 'last' => 'Burnett', 'meal' => 'S')),
        'children'       => 1,
        'email'          => 'james.dahlfred@gmail.com',
        'phone'          => '6036821842',
        'address'        => '414 Franklin Ave, Apt 2, Pittsburgh, PA 15221',
        'appetizer'      => false,
        'note'           => '',
        'accomodations'  => json_encode(array('Sat' => 'Wylie Inn', 'Sun' => 'Salem Harbor Hotel')),
        'created_at'     => new DateTime,
        'updated_at'     => new DateTime
      ),
      array(
        'code'           => 'GA3324',
        'list'           => 'A',
        'attending'      => false,
        'emotion'        => 'regret',
        'allow_plusone'  => true,
        'allow_children' => true,
        'guest'          => json_encode(array('first' => 'Avra', 'last' => 'Ackerman')),
        'plusone'        => json_encode(array('first' => 'Ian', 'last' => 'MacNamara')),
        'children'       => 0,
        'email'          => '',
        'phone'          => '',
        'address'        => '233B Chapel Hill Rd, Atlantic Highlands, NJ 07716',
        'appetizer'      => false,
        'note'           => '',
        'accomodations'  => '',
        'created_at'     => new DateTime,
        'updated_at'     => new DateTime
      ),
      array(
        'code'           => 'BE0875',
        'list'           => 'A',
        'attending'      => false,
        'emotion'        => 'regret',
        'allow_plusone'  => true,
        'allow_children' => true,
        'guest'          => json_encode(array('first' => 'Laura', 'last' => 'Berkebile')),
        'plusone'        => '',
        'children'       => 0,
        'email'          => '',
        'phone'          => '',
        'address'        => '434 Hoodridge Dr, Pittsburgh, PA 15234',
        'appetizer'      => false,
        'note'           => '',
        'accomodations'  => json_encode(array('Sat' => 'Wiley', 'Sun' => 'Wiley')),
        'created_at'     => new DateTime,
        'updated_at'     => new DateTime
      ),
      array(
        'code'           => 'BR2299',
        'list'           => 'A',
        'attending'      => false,
        'emotion'        => 'regret',
        'allow_plusone'  => true,
        'allow_children' => true,
        'guest'          => json_encode(array('first' => 'Ray', 'last' => 'Brown')),
        'plusone'        => json_encode(array('first' => 'Susan', 'last' => 'Brown')),
        'children'       => 0,
        'email'          => '',
        'phone'          => '',
        'address'        => '8 Hazelnut Lane, Londonderry NH 03053',
        'appetizer'      => false,
        'note'           => '',
        'accomodations'  => '',
        'created_at'     => new DateTime,
        'updated_at'     => new DateTime
      ),
      array(
        'code'           => 'BR9129',
        'list'           => 'A',
        'attending'      => false,
        'emotion'        => 'regret',
        'allow_plusone'  => true,
        'allow_children' => false,
        'guest'          => json_encode(array('first' => 'Sam', 'last' => 'Brown')),
        'plusone'        => json_encode(array('first' => 'Guest')),
        'children'       => 0,
        'email'          => '',
        'phone'          => '',
        'address'        => '108 Ives St Apt. 2R, Providence, RI 02906',
        'appetizer'      => false,
        'note'           => '',
        'accomodations'  => '',
        'created_at'     => new DateTime,
        'updated_at'     => new DateTime
      ),
      array(
        'code'           => 'BR9135',
        'list'           => 'A',
        'attending'      => false,
        'emotion'        => 'regret',
        'allow_plusone'  => true,
        'allow_children' => false,
        'guest'          => json_encode(array('first' => 'Emily', 'last' => 'Brown')),
        'plusone'        => json_encode(array('first' => 'Guest')),
        'children'       => 0,
        'email'          => '',
        'phone'          => '',
        'address'        => '51 Parade St #1R, Providence, RI 02909',
        'appetizer'      => false,
        'note'           => '',
        'accomodations'  => '',
        'created_at'     => new DateTime,
        'updated_at'     => new DateTime
      ),
      array(
        'code'           => 'BRANNA',
        'list'           => 'A',
        'attending'      => false,
        'emotion'        => 'regret',
        'allow_plusone'  => false,
        'allow_children' => false,
        'guest'          => json_encode(array('first' => 'Anna', 'last' => 'Brown')),
        'plusone'        => '',
        'children'       => 0,
        'email'          => '',
        'phone'          => '',
        'address'        => '8 Hazelnut Lane, Londonderry, NH 03053',
        'appetizer'      => false,
        'note'           => '',
        'accomodations'  => '',
        'created_at'     => new DateTime,
        'updated_at'     => new DateTime
      ),
      array(
        'code'           => 'BU2499',
        'list'           => 'A',
        'attending'      => false,
        'emotion'        => 'regret',
        'allow_plusone'  => false,
        'allow_children' => false,
        'guest'          => json_encode(array('first' => 'Brian', 'last' => 'Buckland')),
        'plusone'        => json_encode(array('first' => 'Catherine', 'last' => 'Arnold')),
        'children'       => 0,
        'email'          => '',
        'phone'          => '',
        'address'        => '173 Warren St, Newton, MA 02459',
        'appetizer'      => false,
        'note'           => '',
        'accomodations'  => '',
        'created_at'     => new DateTime,
        'updated_at'     => new DateTime
      ),
      array(
        'code'           => 'BU2251',
        'list'           => 'A',
        'attending'      => false,
        'emotion'        => 'regret',
        'allow_plusone'  => false,
        'allow_children' => false,
        'guest'          => json_encode(array('first' => 'Jack', 'last' => 'Burnett')),
        'plusone'        => '',
        'children'       => 0,
        'email'          => '',
        'phone'          => '',
        'address'        => '514 sunset drive, Endwell, NY 13760',
        'appetizer'      => false,
        'note'           => '',
        'accomodations'  => '',
        'created_at'     => new DateTime,
        'updated_at'     => new DateTime
      ),
      array(
        'code'           => 'BU7401',
        'list'           => 'A',
        'attending'      => false,
        'emotion'        => 'regret',
        'allow_plusone'  => false,
        'allow_children' => false,
        'guest'          => json_encode(array('first' => 'James', 'last' => 'Burnett')),
        'plusone'        => '',
        'children'       => 0,
        'email'          => '',
        'phone'          => '',
        'address'        => 'CMR 454 Box 2571, APO AE 09250',
        'appetizer'      => false,
        'note'           => '',
        'accomodations'  => '',
        'created_at'     => new DateTime,
        'updated_at'     => new DateTime
      ),
      array(
        'code'           => 'BU0613',
        'list'           => 'A',
        'attending'      => false,
        'emotion'        => 'regret',
        'allow_plusone'  => false,
        'allow_children' => false,
        'guest'          => json_encode(array('first' => 'Jesse', 'last' => 'Burnett')),
        'plusone'        => json_encode(array('first' => 'Clarissa', 'last' => 'Burnett')),
        'children'       => 3,
        'email'          => '',
        'phone'          => '',
        'address'        => '1 Westchester Rd, Windham, NH 03087',
        'appetizer'      => false,
        'note'           => '',
        'accomodations'  => '',
        'created_at'     => new DateTime,
        'updated_at'     => new DateTime
      ),
      array(
        'code'           => 'BU6828',
        'list'           => 'A',
        'attending'      => false,
        'emotion'        => 'regret',
        'allow_plusone'  => false,
        'allow_children' => false,
        'guest'          => json_encode(array('first' => 'Luke', 'last' => 'Burnett')),
        'plusone'        => json_encode(array('first' => 'Megan', 'last' => 'Burnett')),
        'children'       => 0,
        'email'          => '',
        'phone'          => '',
        'address'        => '4 Ashland St, Beverly, MA 01915',
        'appetizer'      => false,
        'note'           => '',
        'accomodations'  => '',
        'created_at'     => new DateTime,
        'updated_at'     => new DateTime
      ),
      array(
        'code'           => 'BU8645',
        'list'           => 'A',
        'attending'      => false,
        'emotion'        => 'regret',
        'allow_plusone'  => false,
        'allow_children' => false,
        'guest'          => json_encode(array('first' => 'Polly', 'last' => 'Burnett')),
        'plusone'        => json_encode(array('first' => 'Nancy', 'last' => 'Manson')),
        'children'       => 0,
        'email'          => '',
        'phone'          => '',
        'address'        => '238 Holdenwood Rd, Concord, MA 01742',
        'appetizer'      => false,
        'note'           => '',
        'accomodations'  => '',
        'created_at'     => new DateTime,
        'updated_at'     => new DateTime
      )
    );

    DB::table('guests')->insert( $guests );
  }

}

?>
